apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-webinar

resources:
  - vi.yaml
  - vd.yaml
  - vm.yaml
  - expose.yaml   # Service + Ingress + Certificate + NetworkPolicy
