---
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualDisk
metadata:
  name: demo-argocd-root
spec:
  persistentVolumeClaim:
    size: 4Gi
  dataSource:
    type: ObjectRef
    objectRef:
      kind: VirtualImage
      name: ubuntu-26-04-packer
