apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualImage
metadata:
  name: {{ .Values.name }}
spec:
  storage: ContainerRegistry
  dataSource:
    type: HTTP
    http:
      url: {{ .Values.imageUrl }}
